env:
  STACK: java
  BUILD_TECH: java_ant
#   MVN_ARGS: clean install --batch-mode --update-snapshots verify
  CONTINUE_ON_ERROR: false
  CONTINUE_ON_ERROR_SETUP: true
  JOB_STATUS_CODE: 0

on:
  push:
  # and the target with some regex to match specific  branch namess
    branches:
      - master
      - 'FEATURE-[0-9]-[0-9]-[0-9]-X-BRANCH'
      - '[0-9]_[0-9]_x'
      - '[0-9]-[0-9]-X-BRANCH'
  pull_request:
    branches:
      - master
      - 'FEATURE-[0-9]-[0-9]-[0-9]-X-BRANCH'
      - '[0-9]_[0-9]_x'
      - '[0-9]-[0-9]-X-BRANCH'
      
  workflow_dispatch:
  schedule:
    # Runs "at minute 5 past every hour" (see https://crontab.guru)
    - cron: '5 * * * *'

jobs:
  Jab1:
    runs-on: ubuntu-latest 
    
    steps:
    ######## Checkout code ########
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
          
      ######## Setup JDK 11 ########
      - name: set up JDK 11
        id: setup_jdk
        if: ${{ env.STACK == 'java' }}
        uses: actions/setup-java@v2
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
        with:
          java-version: '11'
          distribution: 'adopt'
              
       
      ######## Build - ANT ########       
      - name: Download sonar scanner jar
        run: wget 'https://github.com/junit-team/junit4/releases/download/r4.12/junit-4.12.jar' -O '/home/runner/work/simple-java-maven-app/simple-java-maven-app/lib/junit-4.12.jar'
      
      - name: Build with Ant
        if: ${{ env.BUILD_TECH == 'java_ant'  }}
        run: ant -noinput -buildfile build.xml

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2.2.3
        with:
            name: Jars
            path: /home/runner/work/java-junit-template-project/java-junit-template-project/lib/org.jacoco.ant-0.8.7.jar!/org/jacoco/ant/antlib.xml
        
      - name: files
        run: ls -ltrR

      - name: action is being called here
        uses: nihar30/simple-java-maven-app/.github/actions/print_env_var@master
        with:
          STACK: ${{ env.STACK }}
          BUILD_TECH: ${{ env.BUILD_TECH }}


  Job2:
    uses: nihar30/simple-java-maven-app/.github/workflows/checkmarx-analysis.yml@master
    needs: Jab1
    with: 
      proj_name: 'GithubActionTest'
      teams_path: '\CxServer\SP\Checkmarx'
          